/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.MeioAmbienteController;
import Controller.UsuarioController;
import Model.MeioAmbiente;
import javax.swing.JOptionPane;

/**
 *
 * @author victorsena
 */
public class Questoes extends javax.swing.JFrame {

    public static UsuarioController usuarioController;
    public static String[] usuarioLogado = new String[10];
    public static Menu menu;
    int alternativaCorreta;
    MeioAmbienteController meioAmbienteController = new MeioAmbienteController();
    int numeroQuestao = 0;
    int score = 0;
    
    /**
     * Creates new form Questoes
     */
    public Questoes() {
        initComponents();
        
        this.inserirPerguntas();
        this.setPergunta(0);
    }
    
    public void setUsuarioController(UsuarioController usuarioController) {
        this.usuarioController = usuarioController;
    }
    
    public void setUsuarioLogado(String[] usuarioLogado) {
        this.usuarioLogado = usuarioLogado;
    }
    
    public void setPergunta(int idPergunta){
        String titulo;
        String[] alternativas = new String[8];
        
        titulo = meioAmbienteController.getTituloPergunta(idPergunta);
        alternativaCorreta = meioAmbienteController.getAlternativasCorreta(idPergunta);
        alternativas = meioAmbienteController.getAlternativasPergunta(idPergunta);
        
        txtQuestao.setText(titulo);
        
        labelScore.setText("Score: " + score);
        
        btnAlternativaA.setText(alternativas[0]);
        btnAlternativaB.setText(alternativas[1]);
        btnAlternativaC.setText(alternativas[2]);
        btnAlternativaD.setText(alternativas[3]);
    }
    
    public void setMenu(Menu _menu){
        this.menu = _menu;
    }
    
    public void inserirPerguntas(){
        meioAmbienteController.inserirPerguntas();
    }
    
    public void limpaTela(){
        btnAlternativaA.setText("");
        btnAlternativaB.setText("");
        btnAlternativaC.setText("");
        btnAlternativaD.setText("");
        
        txtQuestao.setText("");
        labelScore.setText("Score: ");
    }
    
    public void validarResposta(int alternativaEscolhida){
        if(meioAmbienteController.validaAlternativa(numeroQuestao, alternativaEscolhida))
        {
            
            score += 10;
            
            if(score != 50)
            {
                numeroQuestao += 1;

                this.setPergunta(numeroQuestao);
            }
            else
            {
                labelScore.setText("Score: " + score);
                
                JOptionPane.showMessageDialog(null, "Parabéns, você venceu !!!!");
                JOptionPane.showMessageDialog(null, "Seu score foi: " + score + ", você receberá em forma de dinheiro a sua compensação.");
                JOptionPane.showMessageDialog(null, "Obrigado, por participar você receberá em alguns dias o valor em sua conta."
                        + "\n Dados da conta :"
                        + "\nNome do Beneficiado: " + usuarioLogado[1] + " " + usuarioLogado[2]
                        + "\nRg: " + usuarioLogado[5]
                        + "\nCpf: " + usuarioLogado[4]
                        + "\nTelefone: " + usuarioLogado[9]
                        + "\nBanco: " + usuarioLogado[8]
                        + "\nAgência: " + usuarioLogado[6]
                        + "\nConta: " + usuarioLogado[7]
                        + "\nValor depositado: R$ " + score + ",00");
                
                this.dispose();
                
                menu.setVisible(true);
            }
            
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Alternativa Incorreta, você perdeu !");
            
            JOptionPane.showMessageDialog(null, "Seu score foi: " + score + ", agradecemos pela participação no jogo, até a Próxima.");
            
            this.dispose();
            
            menu.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtQuestao = new javax.swing.JTextArea();
        btnAlternativaD = new javax.swing.JButton();
        btnAlternativaA = new javax.swing.JButton();
        btnAlternativaB = new javax.swing.JButton();
        btnAlternativaC = new javax.swing.JButton();
        labelScore = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        labelTitulo.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        labelTitulo.setText("EcoQuiz");
        labelTitulo.setAlignmentY(0.0F);

        txtQuestao.setColumns(20);
        txtQuestao.setRows(5);
        txtQuestao.setFocusable(false);
        jScrollPane1.setViewportView(txtQuestao);

        btnAlternativaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlternativaDActionPerformed(evt);
            }
        });

        btnAlternativaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlternativaAActionPerformed(evt);
            }
        });

        btnAlternativaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlternativaBActionPerformed(evt);
            }
        });

        btnAlternativaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlternativaCActionPerformed(evt);
            }
        });

        labelScore.setFont(new java.awt.Font("Ubuntu Light", 1, 14)); // NOI18N
        labelScore.setText("Score:");

        btnSair.setText("Voltar ao Menu");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(labelTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                        .addComponent(labelScore, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAlternativaA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(btnAlternativaD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAlternativaC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAlternativaB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTitulo)
                    .addComponent(labelScore, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnAlternativaA, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAlternativaB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAlternativaC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAlternativaD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        menu.setVisible(true);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnAlternativaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlternativaAActionPerformed
        // TODO add your handling code here:
        this.validarResposta(0);
    }//GEN-LAST:event_btnAlternativaAActionPerformed

    private void btnAlternativaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlternativaBActionPerformed
        // TODO add your handling code here:
        this.validarResposta(1);
    }//GEN-LAST:event_btnAlternativaBActionPerformed

    private void btnAlternativaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlternativaCActionPerformed
        // TODO add your handling code here:
        this.validarResposta(2);
    }//GEN-LAST:event_btnAlternativaCActionPerformed

    private void btnAlternativaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlternativaDActionPerformed
        // TODO add your handling code here:
        this.validarResposta(3);
    }//GEN-LAST:event_btnAlternativaDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Questoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Questoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Questoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Questoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Questoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlternativaA;
    private javax.swing.JButton btnAlternativaB;
    private javax.swing.JButton btnAlternativaC;
    private javax.swing.JButton btnAlternativaD;
    private javax.swing.JButton btnSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelScore;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextArea txtQuestao;
    // End of variables declaration//GEN-END:variables
}
